version: '3'

services:
  jokes:
    build: ./jokes-ms
    ports:
      - '10001:10001'
    environment:
      - MONGO_URI=mongodb://mongo:27017/
    depends_on:
      - mongo
    restart: always

  messages:
    build: ./jokes-ms
    ports:
      - '10002:10002'
    environment:
      - MONGO_URI=mongodb://mongo:27017/
    depends_on:
      - mongo
    restart: always

  ui:
    build:
      context: ./ui-ms
    ports:
      - "80:80"
    depends_on:
      - jokes
      - messages
    environment:
      - JOKES_API_URL=http://jokes:10001
      - MESSAGES_API_URL=http://messages:10002

  mongo:
    image: mongo:latest
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    restart: always

volumes:
  data:

