version: '3'

services:
  jokes:
    build: ./jokes-ms
    ports:
      - '10001:10001'
    environment:
      - MONGO_URI=mongodb://mongo:27017/
    depends_on:
      - mongo
    restart: always

  messages:
    build: ./jokes-ms
    ports:
      - '10002:10002'
    environment:
      - MONGO_URI=mongodb://mongo:27017/
    depends_on:
      - mongo
    restart: always

  ui:
    build: ./ui-ms
    ports:
      - '10000:10000'
    restart: always

  mongo:
    image: mongo:latest
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    restart: always

volumes:
  data:

